# migration script template
"""add totp columns to users

Revision ID: 9f1a2b3c4d5e
Revises: e46b016fb138
Create Date: 2026-09-22 18:38:26.000000

"""

from alembic import op
import sqlalchemy as sa

revision = '9f1a2b3c4d5e'
down_revision = 'e46b016fb138'
branch_labels = None
depends_on = None


def upgrade():
    # This revision adds TOTP two-factor-authentication support to the `users` table.
    # down_revision chain: e46b016fb138 -> 9f1a2b3c4d5e -> b7c3d4e5f6a7 (head).
    # ### commands auto generated by Alembic - please adjust! ###
    # totp_secret: shared secret used to generate/validate 2FA codes (nullable).
    op.add_column('users', sa.Column('totp_secret', sa.String(length=32), nullable=True))
    # totp_enabled: user-facing toggle for whether 2FA is active (default off).
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Roll back the two 2FA columns in reverse order of creation.
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###