"""add site_assets table

Revision ID: a1b2c3d4e5f6
Revises: c1a2b3c4d5e6
Create Date: 2026-09-27 07:34:00.000000

"""
from alembic import op
import sqlalchemy as sa

revision = 'a1b2c3d4e5f6'
down_revision = 'c1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'site_assets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('asset_key', sa.String(length=100), nullable=False),
        sa.Column('data', sa.LargeBinary(length=4294967295), nullable=True),
        sa.Column('mime_type', sa.String(length=100), nullable=True),
        sa.Column('file_size', sa.BigInteger(), nullable=True),
        sa.Column('checksum', sa.String(length=64), nullable=True),
        sa.Column('original_filename', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('asset_key'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_assets')
    # ### end Alembic commands ###
