# migration script template
"""add gateway_order_id column to orders

Revision ID: b7c3d4e5f6a7
Revises: 9f1a2b3c4d5e
Create Date: 2026-09-25 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa

revision = 'b7c3d4e5f6a7'
down_revision = '9f1a2b3c4d5e'
branch_labels = None
depends_on = None


def upgrade():
    # This revision is the current migration HEAD.
    # down_revision chain: e46b016fb138 -> 9f1a2b3c4d5e -> b7c3d4e5f6a7 (head).
    # Stores the payment gateway's own order reference on each order so the
    # payment-callback handler can reconcile gateway callbacks with our Order.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('gateway_order_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the gateway order reference column.
    op.drop_column('orders', 'gateway_order_id')
    # ### end Alembic commands ###