"""add category_media table

Revision ID: c1a2b3c4d5e6
Revises: b7c3d4e5f6a7
Create Date: 2026-09-27 11:18:00.000000

"""
from alembic import op
import sqlalchemy as sa

revision = 'c1a2b3c4d5e6'
down_revision = 'b7c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'category_media',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('media_type', sa.String(length=10), nullable=False),
        sa.Column('media_url', sa.String(length=255), nullable=False),
        sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
        sa.Column('mime_type', sa.String(length=50), nullable=True),
        sa.Column('display_order', sa.Integer(), nullable=True),
        sa.Column('is_primary', sa.Boolean(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('media_data', sa.LargeBinary(length=4294967295), nullable=True),
        sa.Column('thumbnail_data', sa.LargeBinary(length=4294967295), nullable=True),
        sa.Column('file_size', sa.BigInteger(), nullable=True),
        sa.Column('original_filename', sa.String(length=255), nullable=True),
        sa.Column('checksum', sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint("media_type in ('image', 'video')", name='ck_category_media_type'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_media')
    # ### end Alembic commands ###
