# migration script template
"""add in-database media storage

Revision ID: e46b016fb138
Revises:
Create Date: 2026-09-22 20:22:13.239794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = 'e46b016fb138'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # This is the initial migration (down_revision = None) and the base of the
    # chain: e46b016fb138 -> 9f1a2b3c4d5e -> b7c3d4e5f6a7 (head).
    # It moves banner/product-variant media from URL-only columns into BLOB
    # columns stored directly in MySQL, plus a couple of schema housekeeping
    # changes for guest wishlists and review uniqueness.
    # ### commands auto generated by Alembic - please adjust! ###
    # banners: raw image bytes + metadata for in-DB banner storage.
    op.add_column('banners', sa.Column('banner_data', sa.LargeBinary(length=4294967295), nullable=True))
    op.add_column('banners', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('banners', sa.Column('file_size', sa.BigInteger(), nullable=True))
    op.add_column('banners', sa.Column('checksum', sa.String(length=64), nullable=True))
    # product_media: full-size + thumbnail bytes, size, original name and checksum.
    op.add_column('product_media', sa.Column('media_data', sa.LargeBinary(length=4294967295), nullable=True))
    op.add_column('product_media', sa.Column('thumbnail_data', sa.LargeBinary(length=4294967295), nullable=True))
    op.add_column('product_media', sa.Column('file_size', sa.BigInteger(), nullable=True))
    op.add_column('product_media', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('product_media', sa.Column('checksum', sa.String(length=64), nullable=True))
    # product_variants: per-variant cover image stored as a BLOB.
    op.add_column('product_variants', sa.Column('variant_image_data', sa.LargeBinary(length=4294967295), nullable=True))
    op.add_column('product_variants', sa.Column('variant_image_mime', sa.String(length=100), nullable=True))
    # reviews: prevent a user from reviewing the same product more than once.
    op.create_unique_constraint('unique_product_user_review', 'reviews', ['product_id', 'user_id'])
    # wishlist_items: allow anonymous guests to hold wishlist items via a session id.
    op.add_column('wishlist_items', sa.Column('guest_session_id', sa.String(length=100), nullable=True))
    # user_id becomes nullable so a row can be owned by a session instead of a user.
    op.alter_column('wishlist_items', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Roll back in reverse order of upgrade: make user_id non-nullable again,
    # drop the guest session column, the review uniqueness, and every media BLOB.
    op.alter_column('wishlist_items', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('wishlist_items', 'guest_session_id')
    op.drop_constraint('unique_product_user_review', 'reviews', type_='unique')
    op.drop_column('product_variants', 'variant_image_mime')
    op.drop_column('product_variants', 'variant_image_data')
    op.drop_column('product_media', 'checksum')
    op.drop_column('product_media', 'original_filename')
    op.drop_column('product_media', 'file_size')
    op.drop_column('product_media', 'thumbnail_data')
    op.drop_column('product_media', 'media_data')
    op.drop_column('banners', 'checksum')
    op.drop_column('banners', 'file_size')
    op.drop_column('banners', 'mime_type')
    op.drop_column('banners', 'banner_data')
    # ### end Alembic commands ###